version: "3.8"

services:
  myuniverse-casino:
    build: .
    ports:
      - "3000:3000" # Frontend
      - "5000:5000" # Backend API
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
